### ISSUE TITLE
非常好，如果JNI部分开源和配置编译，更受欢迎了

### ISSUE THREAD

**Issue by BadDeveloper2022** [153437803/jpegturbo-compress-v2.0.1#1]
非常好，如果JNI部分开源和配置编译，更受欢迎了
测试看看

**Comment by BadDeveloper2022** [comment]
好像JNI部分有些内存泄漏，内存一直增...
java部分的我重写了释放了bitmap，还是一样
有时间看看哈

**Comment by BadDeveloper2022** [comment]
加上这一行，就可以
 if(tmpdata)
    {
        free(tmpdata);
    }

**Comment by zhxacg** [comment]
这个是编译过程的截图

https://www.jianshu.com/p/fbfc496894ff?utm_campaign=hugo&utm_medium=reader_share&utm_content=note&utm_source=weixin-friends&from=singlemessage

**Comment by zhxacg** [comment]
我用的 deepin 编译环境

**Comment by zhxacg** [comment]
commented about 1 month ago
加上这一行，就可以
if(tmpdata)
{
free(tmpdata);
}

这个是加在哪里呀，生成jpeg的后面吗。可以给个截图吗

**Comment by zhxacg** [comment]
最近抽空看了下, 搞定了
